version: "3.3"
services:
  sslcloud:
    build:
      context: ..
    env_file:
      ../.env
    environment:
      MONGO_DB_URI: mongodb://admin:admin@mongo:27017/
      MONGO_DB_NAME: tokens
    #entrypoint: ["/srv/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/srv/sstcloud-alice-gateway"]
    ports:
    #  - "40000:40000"
      - "8080:80"
    volumes:
      - ./tokens:/tokens
    restart: always
  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
